version: '3'

services:
  db:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - ./data/mongo
    environment:
    - MONGO_DATA_DIR=./data/db
    - MONGO_LOG_DIR=/dev/null
    restart: on-failure
  web:
    depends_on:
    - "db"
    build: .
    ports:
    - "8080:8080"
    command: npm run dev